// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewqncdazywecyocmfpob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cW5jZGF6eXdlY3lvY21mcG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDA0MDEsImV4cCI6MjA2MjQ3NjQwMX0.e86at-0qB-Bnl6kL_DBrb5u9RVTr61PtE3XGT_hOYy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);